server:
  host: "0.0.0.0"
  port: "8080"

grpc:
  host: "0.0.0.0"
  port: "50051"

database:
  driver: "postgres"
  dsn: "user=user password=password dbname=calendar host=db port=5432 sslmode=disable"

logger:
  level: "info"

rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"